//! JNI bridge for the herd-scout Android camera publisher.
//!
//! This is the "phone bolted to anything" side of the herd-scout MVP. The
//! Android app captures camera frames via CameraX (NV12 from
//! `ImageAnalysis.OUTPUT_IMAGE_FORMAT_YUV_420_888`), pushes them across the
//! JNI boundary into a [`CameraFrameSource`], and the Rust side hardware
//! encodes H.264 via Android `MediaCodec` (through `moq-media-android`) and
//! publishes a moq broadcast through `iroh-live`.
//!
//! The desktop side subscribes to the broadcast using the same ticket the
//! phone scanned. Tickets are generated by the desktop side and shown as a
//! QR code; the phone scans, parses, and connects.
//!
//! Threading model:
//!   * `JNI_OnLoad` initializes ndk-context (so `oboe`/`MediaCodec` can find
//!     the JavaVM) and a global tokio multi-thread runtime.
//!   * `connectWithTicket` parses the ticket, binds the iroh endpoint, and
//!     stores all session state in an `Arc<Mutex<SessionHandle>>`. The Arc is
//!     leaked into a `jlong` via [`moq_media_android::handle`].
//!   * `startStreaming` constructs a [`LocalBroadcast`] with a
//!     [`CameraFrameSource`] as its video input and calls `Live::publish`.
//!     The encoder pipeline runs on its own tokio task.
//!   * Camera callback thread (CameraX `ImageAnalysis` analyzer executor) calls
//!     `pushCameraNv12` which briefly locks the session, pushes the frame into
//!     the `CameraFrameSource`, and returns. The encoder picks frames off
//!     asynchronously.
//!   * `disconnect` calls `take_handle` (consuming the Arc), shuts down the
//!     `Live` via the runtime, and returns.

#![cfg(target_os = "android")]

mod logcat;

use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use iroh_live::ticket::LiveTicket;
use iroh_live::Live;
use jni::objects::{JByteArray, JClass, JString};
use jni::sys::{jboolean, jint, jlong};
use jni::{JNIEnv, JavaVM};
use moq_media::codec::VideoCodec;
use moq_media::format::{VideoFrame, VideoPreset};
use moq_media::publish::{LocalBroadcast, VideoInput};
use moq_media_android::camera::{CameraFrameSource, SharedCameraSource};
use moq_media_android::handle;
use rusty_codecs::format::Nv12Planes;
use tokio::runtime::Runtime;
use tracing::{error, info, warn};

// ── Logcat filter ──────────────────────────────────────────────────────────

const LOGCAT_FILTER: &str = "\
    warn,\
    iroh=info,\
    iroh_live=debug,\
    iroh_moq=info,\
    moq_media=debug,\
    hang=info,\
    moq_lite=info,\
    rusty_codecs=info,\
    herd_scout_jni=debug";

// ── JNI lifecycle ──────────────────────────────────────────────────────────

/// Called by the JVM when `System.loadLibrary("herd_scout_jni")` is invoked.
/// Initializes ndk-context so MediaCodec can find the JavaVM, and routes
/// tracing to logcat.
#[unsafe(no_mangle)]
pub extern "system" fn JNI_OnLoad(vm: JavaVM, _reserved: *mut std::ffi::c_void) -> jint {
    // SAFETY: the JVM guarantees `vm` is valid during JNI_OnLoad.
    unsafe {
        ndk_context::initialize_android_context(
            vm.get_java_vm_pointer().cast(),
            std::ptr::null_mut(),
        );
    }
    let _ = logcat::init(LOGCAT_FILTER);
    info!("herd_scout_jni loaded");
    jni::sys::JNI_VERSION_1_6
}

// ── Global runtime ─────────────────────────────────────────────────────────

static RUNTIME: OnceLock<Runtime> = OnceLock::new();

fn runtime() -> &'static Runtime {
    RUNTIME.get_or_init(|| {
        tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .thread_name("herd-scout-jni")
            .build()
            .expect("failed to create tokio runtime")
    })
}

// ── Session handle ─────────────────────────────────────────────────────────

/// All state held for one publishing session. Stored as `Arc<Mutex<_>>` and
/// converted to/from a `jlong` opaque handle on the Kotlin side.
struct SessionHandle {
    /// Live (iroh + moq) instance. Owns the iroh endpoint.
    live: Live,
    /// Parsed ticket the phone scanned. The broadcast is published under
    /// `ticket.broadcast_name` so the desktop subscriber finds it.
    ticket: LiveTicket,
    /// Once `start_streaming` has been called, the broadcast and camera
    /// source live here. `None` between connect and start_streaming.
    streaming: Option<StreamingState>,
    /// Frame counter for the status overlay.
    frames_pushed: u64,
    created_at: Instant,
}

struct StreamingState {
    /// Kept alive to sustain the broadcast publish.
    #[allow(dead_code)]
    broadcast: LocalBroadcast,
    /// Shared with the camera analyzer thread for pushing frames.
    camera_source: Arc<Mutex<CameraFrameSource>>,
    width: u32,
    height: u32,
    started_at: Instant,
}

type SharedHandle = Arc<Mutex<SessionHandle>>;

fn to_jlong(h: SharedHandle) -> jlong {
    handle::to_i64(h)
}

/// # Safety
/// `h` must be a valid handle previously returned by [`to_jlong`] and not
/// yet freed via [`take_handle`].
unsafe fn borrow_handle(h: jlong) -> SharedHandle {
    unsafe { handle::from_i64(h) }
}

/// # Safety
/// `h` must be a valid handle previously returned by [`to_jlong`] and must
/// not be used after this call.
unsafe fn take_handle(h: jlong) -> SharedHandle {
    unsafe { handle::take_i64(h) }
}

fn read_jstring(env: &mut JNIEnv<'_>, s: &JString<'_>) -> Option<String> {
    match env.get_string(s) {
        Ok(s) => Some(s.into()),
        Err(e) => {
            error!("failed to read JNI string: {e}");
            None
        }
    }
}

fn new_jstring<'a>(env: &mut JNIEnv<'a>, s: &str) -> jni::objects::JString<'a> {
    env.new_string(s).unwrap_or_else(|_| {
        env.new_string("")
            .expect("new_string fallback must succeed")
    })
}

// ── JNI: connect ───────────────────────────────────────────────────────────

/// Parses a ticket string, binds the iroh endpoint, and returns an opaque
/// session handle (or 0 on failure).
///
/// The ticket is generated by the desktop side and rendered as a QR code; the
/// phone scans it via CameraX MlKit and passes the decoded string here.
///
/// # Safety
/// Called from JNI; arguments are validated below.
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_herdscout_app_HerdScoutJni_nativeConnectWithTicket(
    mut env: JNIEnv<'_>,
    _class: JClass<'_>,
    ticket: JString<'_>,
) -> jlong {
    let Some(ticket_str) = read_jstring(&mut env, &ticket) else {
        return 0;
    };
    match runtime().block_on(connect_impl(ticket_str)) {
        Ok(h) => h,
        Err(e) => {
            error!("connectWithTicket failed: {e:#}");
            0
        }
    }
}

async fn connect_impl(ticket_str: String) -> Result<jlong> {
    let ticket: LiveTicket = ticket_str
        .trim()
        .parse()
        .context("failed to parse iroh-live ticket")?;
    info!(broadcast = %ticket.broadcast_name, "parsed ticket; binding endpoint");

    // We bind without enabling the Router — the phone is publish-only and
    // dials out to the desktop, no inbound MoQ sessions. with_gossip is also
    // not strictly required for a single named broadcast, but keeps parity
    // with the demo and lets multiple subscribers find us.
    let live = Live::from_env()
        .await
        .context("Live::from_env failed")?
        .with_router()
        .with_gossip()
        .spawn();
    info!(id = %live.endpoint().id().fmt_short(), "endpoint ready");

    let session = SessionHandle {
        live,
        ticket,
        streaming: None,
        frames_pushed: 0,
        created_at: Instant::now(),
    };
    Ok(to_jlong(Arc::new(Mutex::new(session))))
}

// ── JNI: start streaming ───────────────────────────────────────────────────

/// Builds a LocalBroadcast with a CameraFrameSource as its video input and
/// publishes it under the ticket's broadcast name.
///
/// Returns `true` on success, `false` on failure. The session handle remains
/// valid either way; on failure, the caller should `disconnect` to clean up.
///
/// # Safety
/// `handle` must be a live handle from `connectWithTicket`.
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_herdscout_app_HerdScoutJni_nativeStartStreaming(
    _env: JNIEnv<'_>,
    _class: JClass<'_>,
    handle: jlong,
    width: jint,
    height: jint,
) -> jboolean {
    if handle == 0 {
        return jni::sys::JNI_FALSE;
    }
    let session = unsafe { borrow_handle(handle) };
    match runtime().block_on(start_streaming_impl(
        session,
        width as u32,
        height as u32,
    )) {
        Ok(()) => jni::sys::JNI_TRUE,
        Err(e) => {
            error!("startStreaming failed: {e:#}");
            jni::sys::JNI_FALSE
        }
    }
}

async fn start_streaming_impl(
    session: SharedHandle,
    width: u32,
    height: u32,
) -> Result<()> {
    info!(width, height, "starting streaming");

    let camera_source = Arc::new(Mutex::new(CameraFrameSource::new(width, height)));
    let shared_source = SharedCameraSource {
        inner: Arc::clone(&camera_source),
    };

    let broadcast = LocalBroadcast::new();
    let codec = VideoCodec::best_available()
        .context("no video codec available (expected H264 on Android)")?;
    broadcast
        .video()
        .set(VideoInput::new(
            shared_source,
            codec,
            [VideoPreset::P720],
        ))
        .context("failed to set video source on broadcast")?;

    // Take what we need from the session under a short lock, then publish
    // outside the lock so we don't block camera frame pushes.
    let (live, name) = {
        let guard = session
            .lock()
            .map_err(|_| anyhow::anyhow!("session mutex poisoned"))?;
        (guard.live.clone(), guard.ticket.broadcast_name.clone())
    };
    live.publish(&name, &broadcast)
        .await
        .with_context(|| format!("Live::publish('{}') failed", name))?;
    info!(name = %name, "broadcast published");

    let mut guard = session
        .lock()
        .map_err(|_| anyhow::anyhow!("session mutex poisoned"))?;
    guard.streaming = Some(StreamingState {
        broadcast,
        camera_source,
        width,
        height,
        started_at: Instant::now(),
    });
    guard.frames_pushed = 0;
    Ok(())
}

// ── JNI: push NV12 camera frame ────────────────────────────────────────────

/// Pushes an NV12 frame from the CameraX `ImageAnalysis` callback. Both
/// planes are passed as direct byte arrays from Kotlin; strides come from
/// the Camera2 plane metadata and may differ from `width`.
///
/// This is the hot path: called ~30 times/second from the camera analyzer
/// thread. We hold the session mutex only long enough to deposit the frame
/// into the `CameraFrameSource`; the encoder pipeline pulls frames on its
/// own task.
///
/// # Safety
/// `handle` must be a live handle from `connectWithTicket`.
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_herdscout_app_HerdScoutJni_nativePushCameraNv12(
    env: JNIEnv<'_>,
    _class: JClass<'_>,
    handle: jlong,
    y_data: JByteArray<'_>,
    uv_data: JByteArray<'_>,
    width: jint,
    height: jint,
    y_stride: jint,
    uv_stride: jint,
) {
    if handle == 0 {
        return;
    }
    let session = unsafe { borrow_handle(handle) };

    let Ok(y_bytes) = env.convert_byte_array(y_data) else {
        warn!("failed to read Y plane");
        return;
    };
    let Ok(uv_bytes) = env.convert_byte_array(uv_data) else {
        warn!("failed to read UV plane");
        return;
    };

    let mut guard = match session.lock() {
        Ok(g) => g,
        Err(_) => return,
    };

    // Clone the Arc out of the immutable borrow first so we can then
    // mutate the frame counter without overlapping borrows.
    let camera_source = match guard.streaming.as_ref() {
        Some(state) => Arc::clone(&state.camera_source),
        None => {
            // Streaming hasn't started yet — drop the frame.
            return;
        }
    };

    let frame_idx = guard.frames_pushed;
    guard.frames_pushed += 1;
    if frame_idx == 0 {
        info!(
            width,
            height,
            y_stride,
            uv_stride,
            y_len = y_bytes.len(),
            uv_len = uv_bytes.len(),
            "first NV12 camera frame"
        );
    }

    let frame = VideoFrame::new_nv12(
        Nv12Planes {
            y_data: y_bytes,
            y_stride: y_stride as u32,
            uv_data: uv_bytes,
            uv_stride: uv_stride as u32,
            width: width as u32,
            height: height as u32,
        },
        Duration::ZERO,
    );

    drop(guard); // release session lock before touching the source mutex

    if let Ok(mut src) = camera_source.lock() {
        src.push_frame(frame);
    }
}

// ── JNI: stop streaming (keeps the iroh endpoint alive) ───────────────────

/// Stops pushing frames but keeps the iroh endpoint alive so the user can
/// resume without re-scanning. Equivalent to the "Pause" half of the demo
/// flow. After this call, `pushCameraNv12` becomes a no-op until the next
/// `startStreaming`.
///
/// # Safety
/// `handle` must be a live handle from `connectWithTicket`.
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_herdscout_app_HerdScoutJni_nativeStopStreaming(
    _env: JNIEnv<'_>,
    _class: JClass<'_>,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    let session = unsafe { borrow_handle(handle) };
    if let Ok(mut guard) = session.lock() {
        if let Some(state) = guard.streaming.take() {
            info!(
                frames = guard.frames_pushed,
                duration_ms = state.started_at.elapsed().as_millis() as u64,
                "stopped streaming"
            );
        }
    }
}

// ── JNI: disconnect (fully tears down) ─────────────────────────────────────

/// Frees the session handle, dropping the iroh endpoint and the broadcast.
/// The handle must not be used after this call.
///
/// # Safety
/// `handle` must be a live handle from `connectWithTicket` and must not be
/// used after.
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_herdscout_app_HerdScoutJni_nativeDisconnect(
    _env: JNIEnv<'_>,
    _class: JClass<'_>,
    handle: jlong,
) {
    if handle == 0 {
        return;
    }
    let session = unsafe { take_handle(handle) };
    // Shut the Live down on the runtime so any in-flight async work drains.
    if let Ok(guard) = session.lock() {
        let live = guard.live.clone();
        runtime().block_on(live.shutdown());
    }
    info!("disconnected");
}

// ── JNI: status string for the overlay ─────────────────────────────────────

/// Returns a short human-readable status string. Shown in the app's status
/// overlay when streaming is active.
///
/// # Safety
/// `handle` must be a live handle from `connectWithTicket`.
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_herdscout_app_HerdScoutJni_nativeGetStatusLine<'a>(
    mut env: JNIEnv<'a>,
    _class: JClass<'a>,
    handle: jlong,
) -> jni::objects::JString<'a> {
    if handle == 0 {
        return new_jstring(&mut env, "");
    }
    let session = unsafe { borrow_handle(handle) };
    let Ok(guard) = session.lock() else {
        return new_jstring(&mut env, "");
    };
    let elapsed = guard.created_at.elapsed().as_secs();
    let line = match guard.streaming.as_ref() {
        Some(s) => format!(
            "Streaming {}x{} | frames:{} | {}s",
            s.width, s.height, guard.frames_pushed, elapsed
        ),
        None => format!("Connected | {}s", elapsed),
    };
    new_jstring(&mut env, &line)
}

/// Returns the broadcast name from the parsed ticket, for the UI to display.
///
/// # Safety
/// `handle` must be a live handle from `connectWithTicket`.
#[unsafe(no_mangle)]
pub extern "system" fn Java_com_herdscout_app_HerdScoutJni_nativeGetBroadcastName<'a>(
    mut env: JNIEnv<'a>,
    _class: JClass<'a>,
    handle: jlong,
) -> jni::objects::JString<'a> {
    if handle == 0 {
        return new_jstring(&mut env, "");
    }
    let session = unsafe { borrow_handle(handle) };
    let Ok(guard) = session.lock() else {
        return new_jstring(&mut env, "");
    };
    let name = guard.ticket.broadcast_name.clone();
    new_jstring(&mut env, &name)
}
