android.useAndroidX=true
# Use Kotlin's official code style.
kotlin.code.style=official
# Enough heap for AGP + R8 + cargo-ndk piping native lib stripping.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Parallel project execution (we have one module today, but harmless).
org.gradle.parallel=true
# Configuration cache speeds up incremental Gradle invocations.
org.gradle.caching=true
